[package]
name = "mr-t"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "mrt"
path = "src/main.rs"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
rand = "0.10"
semver = "1"
toml = "0.8"

[dev-dependencies]
tempfile = "3"
